name: Sync CI

on:
  schedule:
    - cron: 0 0 * * 0

  workflow_dispatch:
  push:
    branches: ['master']

permissions: write-all

env:
  ACCOUNT_ID: ${{ secrets.GEOLITE_ACCOUNT_ID }}
  LICENSE_KEY: ${{ secrets.GEOLITE_LICENSE_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USER: ${{ github.actor }}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout & Install
        run: sudo apt-get -qq -y update && sudo apt-get install -y axel unzip --no-install-recommends

      - name: Sync
        run: ./sync.sh
