name: Sync CI

on:
  schedule:  
   - cron: 0 0 * * *
   
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions: write-all

env:
  LICENSE_KEY: ${{ secrets.GEOLITE_LICENSE_KEY }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout & Install
      run: sudo apt-get clean all && sudo apt-get -qq -y update && sudo apt-get upgrade -y && sudo apt-get install -y axel && chmod 755 sync.sh
     
    - name: Sync
      run: ./sync.sh
      
      
